/**
 * GeneratorAgent — synthesises a typed, runnable Playwright spec from a
 * validated API definition and writes it to `tests/api/custom/`.
 *
 * Assertion policy: status-only (one assertion per generated test), matching
 * the framework's configured contract. The assertion set is returned so the
 * Reporter can list exactly what was checked.
 */

import fs from 'node:fs';
import path from 'node:path';
import { Agent, AgentContext, GeneratorOutput, PlannerPlan } from './types';
import { absoluteUrl, hasRequestBody, jsSafe, slugify } from './util';
import type { CustomApi, GeneratedAssertion } from '../../src/types';

export class GeneratorAgent extends Agent<{ api: CustomApi; plan: PlannerPlan }, GeneratorOutput> {
  readonly name = 'generator';
  private readonly customSpecDir: string;

  constructor(ctx: AgentContext) {
    super(ctx, 'generator');
    this.customSpecDir = path.join(ctx.frameworkRoot, 'tests', 'api', 'custom');
  }

  run({ api, plan }: { api: CustomApi; plan: PlannerPlan }): GeneratorOutput {
    const source = this.render(api);
    fs.mkdirSync(this.customSpecDir, { recursive: true });
    const specFileAbs = path.join(this.customSpecDir, `${slugify(api.name)}.spec.ts`);
    fs.writeFileSync(specFileAbs, source);
    const specFileRel = path.relative(this.ctx.frameworkRoot, specFileAbs).replace(/\\/g, '/');

    const bytes = Buffer.byteLength(source, 'utf-8');
    const lines = source.split('\n').length;
    this.log.info('spec generated', { specFileRel, lines, bytes });

    return {
      specFileAbs,
      specFileRel,
      source,
      script: { file: specFileRel, lines, bytes, language: 'typescript' },
      assertions: plan.plannedAssertions,
    };
  }

  /** Render the spec source using the framework's Service Object client. */
  private render(api: CustomApi): string {
    const headers: Record<string, string> = {};
    for (const h of api.headers) if (h.key.trim()) headers[h.key] = h.value;
    if (api.auth === 'bearer' && api.bearerToken) headers['Authorization'] = `Bearer ${api.bearerToken}`;
    const query: Record<string, string> = {};
    for (const q of api.query) if (q.key.trim()) query[q.key] = q.value;

    const authKind = api.auth === 'basic' ? 'basic' : api.auth === 'cookie' ? 'cookie' : 'none';
    const hasBody = hasRequestBody(api.method);
    let bodyLiteral = '{}';
    if (hasBody) {
      try {
        bodyLiteral = JSON.stringify(JSON.parse(api.body || '{}'));
      } catch {
        bodyLiteral = '{}';
      }
    }
    const url = absoluteUrl(api);
    const opts = `{
        auth: { kind: '${authKind}' },
        headers: ${JSON.stringify(headers)},
        query: ${JSON.stringify(query)},
        expectedStatus: ${api.expectedStatus},
        skipSchemaValidation: true,
        stepLabel: '${jsSafe(api.name)}',
      }`;
    const verb = api.method.toLowerCase();
    const call = hasBody
      ? `apiClient.${verb}<Record<string, unknown>, unknown>('${url}', ${bodyLiteral} as Record<string, unknown>, ${opts})`
      : `apiClient.${verb}<unknown>('${url}', ${opts})`;

    return `import { test, expect } from '../../../fixtures';

// AUTO-GENERATED by the dashboard Generator agent from a manually-added / imported API.
// Source: ${api.method} ${url}  ·  expects ${api.expectedStatus}
// Assertion policy: status-only.
test.describe('@custom @parallel ${jsSafe(api.name)}', () => {
  test('${jsSafe(api.name)} → ${api.method} ${jsSafe(api.path)} @custom', async ({ apiClient }) => {
    const res = await ${call};
    // Assertion 1 (status): the endpoint returns the expected HTTP status.
    expect(res.status, 'response status === ${api.expectedStatus}').toBe(${api.expectedStatus});
  });
});
`;
  }

  /** The assertions this generator emits for an API (status-only). */
  static assertionsFor(api: CustomApi): GeneratedAssertion[] {
    return [{ label: `response status === ${api.expectedStatus}`, kind: 'status' }];
  }
}
