// Module: api — consolidated Playwright specs (12 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { UsersApi } from '../../api/users-api/users-api.api';
import { getPath } from '../../api/base.api';

test("001 - TC-001 — Verify GET /users/1 returns 200 with a non-empty JSON user object", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-001 — Verify GET /users/1 returns 200 with a non-empty JSON user object");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "header \"content-type\" contains \"application/json\"", '| actual =', String(response.headers()["content-type"] || ''));
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");
  console.log('   ↳ assert:', "JSON \"id\" is present", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\" should exist").toBeDefined();

  console.log("  ✓ TC-001: all 3 assertions passed");
});

test("002 - TC-002 — Confirm GET /users/1 returns id as a number equal to 1", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-002 — Confirm GET /users/1 returns id as a number equal to 1");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is of type number", '| actual =', getPath(body, "id"));
  expect(typeof getPath(body, "id"), "\"id\" should be number").toBe("number");
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-002: all 3 assertions passed");
});

test("003 - TC-003 — Verify GET /users/1 sets a JSON content-type header on the happy path", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-003 — Verify GET /users/1 sets a JSON content-type header on the happy path");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "header \"content-type\" contains \"application/json\"", '| actual =', String(response.headers()["content-type"] || ''));
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");

  console.log("  ✓ TC-003: all 2 assertions passed");
});

test("004 - TC-004 — Verify GET /users/1 responds within 5000ms on the happy path", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-004 — Verify GET /users/1 responds within 5000ms on the happy path");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "response time is under 5000 ms", '| actual =', usersApi.durationMs);
  expect(usersApi.durationMs, 'response time (ms)').toBeLessThan(5000);

  console.log("  ✓ TC-004: all 2 assertions passed");
});

test("005 - TC-005 — Return 404 for GET /users/99999999 when the user id does not exist", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-005 — Return 404 for GET /users/99999999 when the user id does not exist");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/99999999");

  const response = await usersApi.return404ForGETUsers99999999WhenTheUserId();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 404", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(404);

  console.log("  ✓ TC-005: all 1 assertion passed");
});

test("006 - TC-006 — Reject GET /users/abc with a 4xx when the id is non-numeric", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-006 — Reject GET /users/abc with a 4xx when the id is non-numeric");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/abc");

  const response = await usersApi.rejectGETUsersAbcWithA4xxWhenTheIdIsNon();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();
  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-006: all 2 assertions passed");
});

test("007 - TC-007 — Reject POST /users/1 with a 4xx/405 when using an unsupported HTTP method", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-007 — Reject POST /users/1 with a 4xx/405 when using an unsupported HTTP method");
  console.log('  → request:', "POST https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.rejectPOSTUsers1WithA4xx405WhenUsingAn();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();
  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-007: all 2 assertions passed");
});

test("008 - TC-008 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-008 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1?foo=bar");

  const response = await usersApi.confirmGETUsers1IgnoresAnUnknownQuery();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-008: all 2 assertions passed");
});

test("009 - TC-009 — Verify GET /users/10 returns 200 for the highest valid user id in the collection", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-009 — Verify GET /users/10 returns 200 for the highest valid user id in the collection");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/10");

  const response = await usersApi.verifyGETUsers10Returns200ForTheHighestValid();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 10", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(10);

  console.log("  ✓ TC-009: all 2 assertions passed");
});

test("010 - TC-010 — Return 404 for GET /users/0 when the id is below the valid range", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-010 — Return 404 for GET /users/0 when the id is below the valid range");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/0");

  const response = await usersApi.return404ForGETUsers0WhenTheIdIsBelowThe();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 404", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(404);

  console.log("  ✓ TC-010: all 1 assertion passed");
});

test("011 - TC-011 — Confirm GET /users/1 returns identical status on two consecutive requests (idempotency)", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-011 — Confirm GET /users/1 returns identical status on two consecutive requests (idempotency)");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-011: all 2 assertions passed");
});

test("012 - TC-012 — Reject GET /users/-1 with a 4xx/404 when the id is negative", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-012 — Reject GET /users/-1 with a 4xx/404 when the id is negative");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/-1");

  const response = await usersApi.rejectGETUsers1WithA4xx404WhenTheIdIs();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();
  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-012: all 2 assertions passed");
});
