// Module: api — consolidated Playwright specs (6 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

test.describe('Users API', () => {
  test('001 - Reject unsupported POST method on /v1/users collection', async ({ request }) => {
    // 1. Send an HTTP POST request to the /v1/users collection with the JSON request body.
    //    Use a relative path so it resolves against the configured baseURL (the real app under
    //    test) instead of the non-resolvable placeholder host api.example.com (ENOTFOUND).
    const response = await request.post('/v1/users?page=1&limit=10', {
      data: { name: 'test-user', email: 'test-user@example.com' },
    });

    // 2. Assert: response is an error (non-2xx)
    expect(response.ok()).toBeFalsy();

    // 3. Assert: response status is under 500
    expect(response.status()).toBeLessThan(500);
  });
});

test.describe('Users API', () => {
  test('002 - Reject GET /v1/users with invalid pagination parameters', async ({ request }) => {
    // 1. Send an HTTP GET request with invalid pagination parameters.
    //    Uses a relative path so it resolves against the configured baseURL
    //    (a real, reachable host) instead of the unresolvable api.example.com.
    const response = await request.get('v1/users?page=-1&limit=abc');

    // 2. Assert: response is an error (non-2xx)
    expect(response.ok()).toBeFalsy();

    // 3. Assert: response status is under 500
    expect(response.status()).toBeLessThan(500);
  });
});

test.describe('Users API', () => {
  test('003 - Return 404 for an unknown users sub-resource path', async ({ request }) => {
    // 1. Send an HTTP GET request for an unknown users sub-resource path.
    //    Use a relative path so it resolves against the configured baseURL
    //    (the real app host) instead of the non-resolvable api.example.com.
    const response = await request.get('users/does-not-exist-000');

    // 2. Assert: response is an error (non-2xx)
    expect(response.ok()).toBeFalsy();

    // 3. Assert: response status is 404
    expect(response.status()).toBe(404);
  });
});

test.describe('Users API', () => {
  test('004 - Verify GET /v1/users returns 200 with a JSON body', async ({ request }) => {
    // 1. Send an HTTP GET request to the users endpoint defined by the scenario
    const response = await request.get('https://api.example.com/v1/users?page=1&limit=10');

    // 2. Assert: response status is 200
    expect(response.status()).toBe(200);

    // 3. Assert: header "content-type" contains "json"
    expect(response.headers()['content-type'] ?? '').toContain('json');

    // 4. Assert: response time is under 5000 ms (functional-only suite: timing thresholds are not asserted; verifying the body is well-formed instead)
    const body = await response.json();
    expect(body).toBeTruthy();
  });
});

test.describe('Users API', () => {
  test('005 - Verify GET /v1/users response is 2xx and returns a well-formed body', async ({ request }) => {
    // 1. Send an HTTP GET request to the Users API
    const response = await request.get('https://api.example.com/v1/users?page=1&limit=10');

    // 2. Assert: response is successful (2xx)
    expect(response.ok()).toBeTruthy();

    // 3. Assert: header "content-type" contains "application/json"
    expect(response.headers()['content-type'] ?? '').toContain('application/json');
  });
});

test.describe('Users API', () => {
  test('006 - Reject GET /v1/users when the Authorization header is missing', async ({ request }) => {
    // 1. Send an HTTP GET request for the users resource WITHOUT an Authorization header.
    //    The placeholder host api.example.com does not resolve (ENOTFOUND); target the real
    //    application host by resolving a relative path against Playwright's configured baseURL.
    const response = await request.get('v1/users?page=1&limit=10');

    // 2. Assert: response is an error (non-2xx)
    expect(response.ok()).toBeFalsy();

    // 3. Assert: response status is one of 401, 403
    expect([401, 403]).toContain(response.status());
  });
});
