// Module: api — consolidated Playwright specs (5 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

function getPath(obj: any, path: string): any {
  if (!path) return obj;
  return path.split('.').reduce((o: any, k: string) => (o == null ? undefined : o[k]), obj);
}

test("001 - TC-001 — Verify GET /posts returns 200 with a non-empty JSON array of posts", async ({ request }) => {
  const start = Date.now();
  const response = await request.get("https://jsonplaceholder.typicode.com/posts", {
    headers: {"Accept":"application/json"},
  });
  const elapsedMs = Date.now() - start;
  let body: any;
  try { body = await response.json(); } catch (e) { throw new Error('Expected a JSON response body but it did not parse: ' + (e as Error).message); }
  expect(response.status(), 'HTTP status code').toBe(200);
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");
  expect(Array.isArray(body), 'response should be an array').toBeTruthy();
  expect((body || []).length, 'array should not be empty').toBeGreaterThan(0);
  expect(elapsedMs, 'response time (ms)').toBeLessThan(5000);
});

function getPath(obj: any, path: string): any {
  if (!path) return obj;
  return path.split('.').reduce((o: any, k: string) => (o == null ? undefined : o[k]), obj);
}

test("002 - TC-002 — Verify each post in GET /posts carries the documented schema (userId, id, title, body)", async ({ request }) => {
  const start = Date.now();
  const response = await request.get("https://jsonplaceholder.typicode.com/posts", {
    headers: {"Accept":"application/json"},
  });
  const elapsedMs = Date.now() - start;
  let body: any;
  try { body = await response.json(); } catch (e) { throw new Error('Expected a JSON response body but it did not parse: ' + (e as Error).message); }
  expect(response.status(), 'HTTP status code').toBe(200);
  expect(getPath(body, "0.userId"), "property \"0.userId\" should exist").toBeDefined();
  expect(typeof getPath(body, "0.userId"), "\"0.userId\" should be number").toBe("number");
  expect(typeof getPath(body, "0.id"), "\"0.id\" should be number").toBe("number");
  expect(getPath(body, "0.id"), "property \"0.id\"").toEqual(1);
  expect(typeof getPath(body, "0.title"), "\"0.title\" should be string").toBe("string");
  expect(typeof getPath(body, "0.body"), "\"0.body\" should be string").toBe("string");
});

test("003 - TC-003 — Reject GET /posts/99999999 for a non-existent post id (404)", async ({ request }) => {
  const start = Date.now();
  const response = await request.get("https://jsonplaceholder.typicode.com/posts/99999999", {
    headers: {"Accept":"application/json"},
  });
  const elapsedMs = Date.now() - start;
  expect(response.status(), 'HTTP status code').toBe(404);
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();
});

test("004 - TC-004 — Handle GET /posts/abc with a non-numeric id without a server error (4xx)", async ({ request }) => {
  const start = Date.now();
  const response = await request.get("https://jsonplaceholder.typicode.com/posts/abc", {
    headers: {"Accept":"application/json"},
  });
  const elapsedMs = Date.now() - start;
  expect([400,404], 'HTTP status code').toContain(response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();
});

function getPath(obj: any, path: string): any {
  if (!path) return obj;
  return path.split('.').reduce((o: any, k: string) => (o == null ? undefined : o[k]), obj);
}

test("005 - TC-005 — Confirm GET /posts?userId=1 filters and still returns 200 with a non-empty array", async ({ request }) => {
  const start = Date.now();
  const response = await request.get("https://jsonplaceholder.typicode.com/posts?userId=1", {
    headers: {"Accept":"application/json"},
  });
  const elapsedMs = Date.now() - start;
  let body: any;
  try { body = await response.json(); } catch (e) { throw new Error('Expected a JSON response body but it did not parse: ' + (e as Error).message); }
  expect(response.status(), 'HTTP status code').toBe(200);
  expect(Array.isArray(body), 'response should be an array').toBeTruthy();
  expect((body || []).length, 'array should not be empty').toBeGreaterThan(0);
  expect(getPath(body, "0.userId"), "property \"0.userId\"").toEqual(1);
});
