/**
 * Fully-typed DTOs for every request/response payload.
 * Generated by the Generator agent from spec/openapi.json component schemas.
 *
 * MANDATE: `any` is forbidden. Every payload crossing the wire has a type here.
 */

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------
export interface AuthRequest {
  username: string;
  password: string;
}

/** restful-booker returns 200 for both success and bad credentials. */
export interface AuthResponse {
  token?: string;
  reason?: string;
}

// ---------------------------------------------------------------------------
// Booking
// ---------------------------------------------------------------------------
export interface BookingDates {
  /** ISO date, format: date (YYYY-MM-DD). */
  checkin: string;
  checkout: string;
}

export interface Booking {
  firstname: string;
  lastname: string;
  totalprice: number;
  depositpaid: boolean;
  bookingdates: BookingDates;
  additionalneeds?: string;
}

/** PATCH accepts any non-empty subset of Booking fields. */
export type BookingPatch = Partial<Booking>;

export interface CreateBookingResponse {
  bookingid: number;
  booking: Booking;
}

export interface BookingIdRef {
  bookingid: number;
}

export type BookingIdList = BookingIdRef[];

// ---------------------------------------------------------------------------
// HTTP primitives
// ---------------------------------------------------------------------------
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/** Discriminated auth strategy for a request. */
export type AuthStrategy =
  | { kind: 'none' }
  | { kind: 'cookie' } // token injected as `Cookie: token=<token>`
  | { kind: 'basic' }; // Authorization: Basic base64(user:pass)

export interface RequestOptions<TBody> {
  method: HttpMethod;
  path: string;
  body?: TBody;
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  auth?: AuthStrategy;
  /** Expected status for the happy path; used to decide schema validation + logging level. */
  expectedStatus?: number;
  /** Skip the automatic OpenAPI schema validation for this call (e.g. negative tests). */
  skipSchemaValidation?: boolean;
  /** Component schema name to validate the response body against (from spec/openapi.json). */
  responseSchema?: string;
  /** Human label for the test.step wrapping this request. */
  stepLabel?: string;
}

export interface ApiResponse<TData> {
  status: number;
  ok: boolean;
  data: TData;
  headers: Record<string, string>;
  /** Round-trip latency in ms. */
  durationMs: number;
  rawBody: string;
}
