import { test, expect } from '../../../fixtures';

// AUTO-GENERATED by the dashboard Generator agent from a manually-added / imported API.
// Source: GET https://restful-booker.herokuapp.com/booking  ·  expects 200
// Assertion policy: status-only.
test.describe('@custom @parallel Get all bookings', () => {
  test('Get all bookings → GET /booking @custom', async ({ apiClient }) => {
    const res = await apiClient.get<unknown>('https://restful-booker.herokuapp.com/booking', {
        auth: { kind: 'none' },
        headers: {},
        query: {},
        expectedStatus: 200,
        skipSchemaValidation: true,
        stepLabel: 'Get all bookings',
      });
    // Assertion 1 (status): the endpoint returns the expected HTTP status.
    expect(res.status, 'response status === 200').toBe(200);
  });
});
